version: '3'
services:
  rails: &app-base
    build:
      context: .
      dockerfile: build/production.Dockerfile
      args:
        RAILS_ENV: production
    command: bundle exec rails server -b 0.0.0.0 -p '3000'
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
    environment:
      LANG: 'C.UTF-8'
      RAILS_ENV: production
      POSTGRES_HOST: db
      REDIS_URL: redis://redis:6379/0
    env_file:
      - secrets.env
    stdin_open: true
    tty: true


  worker:
    <<: *app-base
    ports: []
    command: bundle exec sidekiq -C config/sidekiq.yml


  db:
    image: postgres:13.1-alpine
    ports:
      - '5432:5432'
    environment:
      PGDATA: /var/lib/postgresql/data
    env_file:
      - secrets.env
    volumes:
      - postgres-data:/var/lib/postgresql/data


  redis:
    image: redis:5.0.7-alpine
    ports:
      - '6379:6379'
    command: [redis-server, --loglevel, notice]
    volumes:
      - redis-data:/data


volumes:
  postgres-data: {}
  redis-data: {}
